server {
    listen 80;

    location /auth {
        proxy_pass http://server:3000;
        proxy_set_header Host $host;
    }

    location /tasks {
        proxy_pass http://server:3000;
        proxy_set_header Host $host;
    }

    location /categories {
        proxy_pass http://server:3000;
        proxy_set_header Host $host;
    }

    location /health {
        proxy_pass http://server:3000;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://client:80;
    }
}